// src/lib/ai-chat-types.ts
//
// Shared types for the AI chat feature. Single source of truth — imported
// by ai-chat-store, ai-chat-tools, chat-orchestrator, native-host-bridge,
// and ChatSection.

export type ChatRole = "user" | "assistant" | "tool" | "system"

export interface ChatMessage {
  id: string                  // ulid()
  role: ChatRole
  content: string             // user text, assistant prose, or JSON-encoded tool result
  toolCall?: ToolCall         // present on assistant messages that emitted one
  toolCallId?: string         // present on tool messages — the toolCall.id they answer
  toolError?: string          // present on tool messages that errored
  ambient?: AmbientContext    // present on user messages — what state we attached
  turnId: string              // groups user + N tool round-trips + assistant for one Send
  createdAt: string           // ISO timestamp
}

export interface ToolCall {
  id: string                  // ulid() — matches tool messages back to the assistant call
  name: string                // e.g. "joplin.createNote"
  arguments: Record<string, unknown>  // parsed from argumentsRaw
  argumentsRaw: string        // exact JSON the model emitted
}

export interface AmbientContext {
  activeTab?: { url: string; title: string }
  mostRecentClip?: { title: string; mode: string; createdAt: string; joplinUrl: string }
  recentScrape?: { url: string; title: string; text: string; timestamp: number }
}

export interface Conversation {
  messages: ChatMessage[]     // append-only at runtime, newest at the end
  compactedHead?: { summary: string; truncatedThrough: string /* last message id covered */ }
}

export type JSONSchema = Record<string, unknown>

export interface ToolDefinition {
  name: string                // dotted namespace: "joplin.createNote", "context.activeTab"
  description: string         // one-sentence; goes into the model prompt
  parametersSchema: JSONSchema
  execute(args: Record<string, unknown>): Promise<ToolExecutionResult>
}

export interface ToolExecutionResult {
  ok: boolean
  result?: unknown            // JSON-stringified into next-turn prompt
  error?: string              // present when ok === false
}

export interface ChatSendRequest {
  type: "ai-chat/send"
  userMessageId: string       // pre-generated by sidebar for optimistic render
  text: string
  ambient: AmbientContext
}

export interface ChatStopRequest {
  type: "ai-chat/stop"
  turnId: string
}

export interface ChatTurnUpdateEvent {
  type: "ai-chat/turn-update"
  turnId: string
  appendedMessage: ChatMessage
}

export interface ChatTurnDoneEvent {
  type: "ai-chat/turn-done"
  turnId: string
  reason: "final" | "stopped" | "step-cap" | "error"
  errorMessage?: string
}
