#!/bin/bash
# Auto-generated by scripts/install-native-host.mjs.
# Re-running install regenerates this with the current node binary.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
HOST_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ "$(uname -s)" = "Darwin" ]; then
  for f in \
    "$HOST_DIR"/node_modules/.pnpm/node-pty@*/node_modules/node-pty/build/Release/pty.node \
    "$HOST_DIR"/node_modules/.pnpm/node-pty@*/node_modules/node-pty/build/Release/spawn-helper \
    "$HOST_DIR"/node_modules/.pnpm/node-pty@*/node_modules/node-pty/prebuilds/darwin-arm64/pty.node \
    "$HOST_DIR"/node_modules/.pnpm/node-pty@*/node_modules/node-pty/prebuilds/darwin-arm64/spawn-helper \
    "$HOST_DIR"/node_modules/.pnpm/node-pty@*/node_modules/node-pty/prebuilds/darwin-x64/pty.node \
    "$HOST_DIR"/node_modules/.pnpm/node-pty@*/node_modules/node-pty/prebuilds/darwin-x64/spawn-helper; do
    [ -e "$f" ] || continue
    /usr/bin/xattr -d com.apple.quarantine "$f" 2>/dev/null || true
    /usr/bin/xattr -d com.apple.provenance "$f" 2>/dev/null || true
    /usr/bin/xattr -d com.apple.macl "$f" 2>/dev/null || true
  done
fi
exec "/Users/aloe/.vite-plus/js_runtime/node/24.16.0/bin/node" "/Users/aloe/Development/ai-dev-sidebar/native-host/ai-dev-host.mjs" "$@"
