#!/bin/bash
# Auto-generated by scripts/install-native-host.mjs.
# Re-running install regenerates this with the current node binary.
exec "/Users/aloe/.vite-plus/js_runtime/node/24.15.0/bin/node" "/Users/aloe/Development/ai-dev-sidebar/native-host/ai-dev-host.mjs" "$@"
